name: app_home_iot
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_switch: ^0.3.2
  web_socket_channel: ^2.4.0
  http: ^0.13.5
  anim_search_bar: ^2.0.3
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  weather: ^3.0.0
  firebase_analytics: ^10.7.4
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/cloudy.png
    - assets/image/weather-app.png
    - assets/icon/sofa_icon.png
    - assets/image/thermometer.png
    - assets/image/lamp.png
    - assets/image/humidity.png
    - assets/image/lamp_off.png
    - assets/image/lamp_on.png
